ci: Update style check workflow to error on go fmt failure

diff --git a/.github/workflows/lint-and-test.yml b/.github/workflows/lint-and-test.yml
--- a/.github/workflows/lint-and-test.yml
+++ b/.github/workflows/lint-and-test.yml
@@ -44,14 +44,22 @@ jobs:
       - name: Download dependencies
         run: go mod download
 
-      - name: Install revive
-        run: go install github.com/mgechev/revive@v1.3.9
+      - name: Install and run revive
+        run: |
+          go install github.com/mgechev/revive@v1.3.9
+          pkgs=$(go list ./... | grep -v $(go env GOMODCACHE))
+          go list $pkgs | grep -v $(go env GOMODCACHE) | xargs -L1 revive -config .revive.toml -set_exit_status
 
       - name: Run go fmt
         run: |
           pkgs=$(go list ./... | grep -v $(go env GOMODCACHE))
           go fmt $pkgs
-          go list $pkgs | grep -v $(go env GOMODCACHE) | xargs -L1 revive -config .revive.toml -set_exit_status
+          # check if there are any changes, if there are then exit with an error that go fmt must be run and changes committed
+          if git diff --quiet; then
+            echo "::error::go fmt was unclean on the following files:"
+            git diff --name-only
+            exit 1
+          fi
 
   # ============================================================================
   # Lint Go Job - Static analysis
